-- Create contact submissions table
create table public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table public.contact_submissions enable row level security;

-- Create policy to allow anonymous inserts
create policy "Allow anonymous inserts"
on public.contact_submissions
for insert
to anon
with check (true);

-- Create policy to allow authenticated users (like you in the Supabase dashboard) to view submissions
create policy "Allow authenticated selects"
on public.contact_submissions
for select
to authenticated
using (true);
